### ISSUE TITLE
Plugin won't activate

### ISSUE THREAD

**Issue by davidqhog** [wallmanderco/elasticsearch-indexer#10]
Hi Mikael, Finally got round to trying this and get this on trying to activate:

Warning: require_once(/home/v33b4s3/public_html/jaycore.co.uk/wp-content/plugins/elasticsearch-indexer-master/vendor/autoload.php): failed to open stream: No such file or directory in /home/v33b4s3/public_html/jaycore.co.uk/wp-content/plugins/elasticsearch-indexer-master/bootstrap.php on line 16

Fatal error: require_once(): Failed opening required '/home/v33b4s3/public_html/jaycore.co.uk/wp-content/plugins/elasticsearch-indexer-master/vendor/autoload.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/v33b4s3/public_html/jaycore.co.uk/wp-content/plugins/elasticsearch-indexer-master/bootstrap.php on line 16

Fatal error: require_once(): Failed opening required '/home/v33b4s3/public_html/jaycore.co.uk/wp-content/plugins/elasticsearch-indexer-master/vendor/autoload.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/v33b4s3/public_html/jaycore.co.uk/wp-content/plugins/elasticsearch-indexer-master/bootstrap.php on line 16

Using the latest zip file from GIT.

Regards,

David Q

**Comment by mikaelmattsson** [comment]
I'm guessing you didn't follow the instructions:
https://github.com/wallmanderco/elasticsearch-indexer#installing-the-plugin-from-github

If you are unfamiliar with composer then I recommend that you install from wordpress.org:
https://wordpress.org/plugins/elasticsearch-indexer/
