### ISSUE TITLE
WooCommerce orders indexing

### ISSUE THREAD

**Issue by MarkGavalda** [wallmanderco/elasticsearch-indexer#2]
One of the weakest points of WC is that its orders search function takes ages when you have a lot of orders. It would be great to leverage ES for this too!

**Comment by mikaelmattsson** [comment]
Should be possible. I wasn't aware that this was a common problem. I will look into it. :+1:

**Comment by MarkGavalda** [comment]
Thanks Mikael it would be awesome. :)

**Comment by mikaelmattsson** [comment]
Added.
