### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by MarkGavalda** [wallmanderco/elasticsearch-indexer#6]
"PHP message: PHP Fatal error:  Call to undefined method Wallmander\ElasticsearchIndexer\Model\Client::getIndices() in /wp-content/plugins/elasticsearch-indexer/src/Controller/Admin.php on line 90" while reading upstream, request: "GET /wp-admin/admin.php?page=esindexer_status

**Comment by mikaelmattsson** [comment]
Ok, I know what the problem is. I'll fix it as soon as possible. That page isn't very inportant. It's just a nice wrapper for [_cat/indices?v](https://www.elastic.co/guide/en/elasticsearch/reference/1.5/cat-indices.html)
