### ISSUE TITLE
Host admin setting not intuitive / restrictive

### ISSUE THREAD

**Issue by achilles283** [wallmanderco/elasticsearch-indexer#7]
Initially entered the full URL to my hosted ES instance in the "Host" admin field (https://xxx.bonsai.io/) and received the following error:

`Uncaught exception 'Elasticsearch\Common\Exceptions\TransportException' with message 'Unknown SSL protocol error in connection to ...`

It would be nice to include example formats expected in the "Host" field in the admin settings panel and/or documentation.

Should also update httpGet, httpPost, and httpPut functions in ElasticSearch.php to allow https connections.

**Comment by mikaelmattsson** [comment]
Can you confirm that it is working now?

**Comment by mikaelmattsson** [comment]
I have confirmed that https is working now. You will have to specify the port when using https. elasticsearch-php defaults to 80 even when using https when it should use 443. I've updated the settings panel to refect this problem. The configuration now accepts urls with and without the protocol-prefix and defaults to http.
