### ISSUE TITLE
update_post_meta not refreshing index

### ISSUE THREAD

**Issue by hriad** [wallmanderco/elasticsearch-indexer#8]
Calling update_post_meta() does not trigger an index refresh. 

As a temporary fix, I'm calling wp_update_post () after update_post_meta(). But this is not efficient at all, as it results in additional database queries.

**Comment by mikaelmattsson** [comment]
Thanks! I will fix this as soon as possible.

**Comment by mikaelmattsson** [comment]
@hriad, I closed this because I considered it fixed. But don't hesitate to comment if you are unsatisfied with the result.

**Comment by hriad** [comment]
@mikaelmattsson, Indded the issue is fixed and it's working as expected now. Thank you.
