### ISSUE TITLE
integration with WPML

### ISSUE THREAD

**Issue by chrisbataille** [wallmanderco/elasticsearch-indexer#9]
Hello,
first of all thanks for this awesome work, it really helps in gettting a faster/better search for wordpress websites.

I am using WPML for multilingual and i would like to know how could i make sure i only display the results in the proper language ?
I saw in the change log that the plugin now integrates with WPML since 1.6.1, but out of the box if i do a standard search query ?s=what+i+m+looking+for&lang=fr i would get all results matching in all languages

Thanks in advance for your help.

**Comment by mikaelmattsson** [comment]
I'm sorry but I'm unable to test this at the moment.
I have a theory that maybe increasing the priority of these lines would help https://github.com/wallmanderco/elasticsearch-indexer/blob/master/src/Hooks.php#L133-L142
Maybe you can test this and tell me how it goes?
